import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import AuthProvider from "./component/AuthProvider";

// const inter = Inter({ subsets: ['latin'] })
// const poppins = Poppins({weight:'500',subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar />
          <div className="">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
